### PR TITLE
Provide public access when the Node-RED server has no public-IP or behind firewall

### PR DESCRIPTION
**Pull request by tronium**

### CODE REVIEW

**Comment by martin-doyle** [comment]
Since the tests failed I do not want to merge the changes into the master branch but into sw_path.

**Comment by martin-doyle** [comment]
I added your changes in the branch ws_path and made some minor cleanups in order to pass semistandard requirements. In addition, I checked the new feature with HiveMQ Websocket client and added a test.
Thanks again.

**Review by martin-doyle — COMMENTED** [review]
I copied your changes and fixed the issues which caused the tests to fail. So, all your changes  are implemented. Thanks again.
Should we close the pull request?

**Comment by tronium** [comment]
Yes @martin-doyle, the PR can be closed.

**Pull request closed without merging**
